config/routes.rb
Rails.application.routes.draw do
  resources :tags
  resources :books
  resources :rakutenbooks, only: [:new, :index]
  
  
  get 'search' => 'books#search'
  get 'loading' => 'tags#loading'

  # modalで削除確認画面実装(book)
  get 'books/:id/deletemodal' => 'books#deletemodal', as: 'deletemodal'
  # modalで削除確認画面実装(tag)
  get 'tags/:id/deletemodal' => 'tags#tagdeletemodal', as: 'tagdeletemodal'

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'   
  } 

  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy" 
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root to: "home#index"
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many:book_tags, dependent: :destroy
  has_many:tags, through: :book_tags
  accepts_nested_attributes_for :book_tags
  
  validates :title, presence: true, uniqueness: { scope: :user }
  default_scope -> { order(created_at: :desc) }
  
  
   def self.looks(search, keyword)
    if search == "perfect_match"
      @books = Book.where("title LIKE?","#{keyword}")
    elsif search == "partial_match"
       if keyword.blank?
         @books = nil
       else
         @books = Book.where("title LIKE?","%#{keyword}%")
       end
    else
      @books = Book.all
    end
   end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books
  has_many :tags
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_book, only: [:edit, :update, :destroy, :deletemodal]
  before_action :api, only: [:index]
  

  # GET /books
  def index
  end
    

  def search
  @books = current_user.books.all.looks(params[:search], params[:keyword])
  @keyword = params[:keyword]
  end


  # GET /books/new
  def new
    @book = current_user.books.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  def create
    @book = current_user.books.new(book_params)
    @rakuten_books_full = []
    if @book.save
       @title = current_user.books.pluck(:title)[0]
       @rakuten_books = RakutenWebService::Books::Book.search(title: @title, sort: '-releaseDate', hits: 1)
       book_page_count = @rakuten_books.response["pageCount"]
       @rakuten_books_title = @rakuten_books.params[:title]
           @rakuten_books.each do |book|
             @rakuten_books_full.push(book)
           end
       @books_info = @rakuten_books_full           
       @status = true
    else
       render :new
       @status = false
    end
  end

  # PATCH/PUT /books/1
  def update
    if @book.update(book_params)
       @title = @book.title
       @rakuten_books_full = []
       @rakuten_books = RakutenWebService::Books::Book.search(title: @title, sort: '-releaseDate', hits:1)
       @rakuten_books.each do |book|
        @rakuten_books_full.push(book)
       end
      @books_info = @rakuten_books_full
       @status = true
    else
      render :edit
      @status = false
    end
  end

  def deletemodal
  end

  # DELETE /books/1
  def destroy
    if @book.destroy
      @status = true
      respond_to do |format|
        format.html { redirect_to books_url, notice: "削除しました。" }
      end
    else
      render :index
      @status = false
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      
      @book = current_user.books.find_by(id: params[:id])
      redirect_to(books_url, alert: "ERROR!!") if @book.blank?

    end

    # Only allow a trusted parameter "white list" through.
    def book_params
      params.require(:book).permit(:title, :user_id, tag_ids: [])
    end

    def api
    #books
     sortbooks = Book.order(:created_at)
     @allbooks = current_user.books.all
     @total_count = current_user.books.count
     @counter = (@total_count+1)
     @rakuten_books_full = []
     @books_full = []
     if @total_count >= 1 
       @allbooks.each do |book|
         @books_full.push(book)
       end
       @books = @books_full
     else
       @books = @allbooks
     end
     #books_info
     if @total_count >= 1
       (@total_count).times do |i|
         @title = current_user.books.pluck(:title)[i]
           @rakuten_books = RakutenWebService::Books::Book.search(title: @title, sort: '-releaseDate', hits: 1)
             if @rakuten_books.response["hits"] == 0
                  @rakuten_books = RakutenWebService::Books::Book.search(title: "クジラの進化", sort: '-releaseDate', hits: 1)
                    @rakuten_books.each do |book|
                      @rakuten_books_full.push(book)
                    end
             else
                @rakuten_books = RakutenWebService::Books::Book.search(title: @title, sort: '-releaseDate', hits: 1)
                  @rakuten_books_title = @rakuten_books.params[:title]
                    @rakuten_books.each do |book|
                      @rakuten_books_full.push(book)
                    end
             end
       end
       @books_info = @rakuten_books_full
     else
       @books_info = nil
     end
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<% if @books_info.present? %>
  <% (@books_info).each do |info| %>
    <div class="card mb-3" data-model_name="<%= Book.model_name.singular %>"
    data-id="<%= book.id %>">
      <div class="card-body">
       <p class="card-text">
         <div class="cen">
          <div class="col-2">
           <% if book.title == info.title %>
            <%= link_to (image_tag(info.medium_image_url)), info.item_url %>
           <% else %>
           <p class="badge badge-danger">no-image</p>
           <% end %> 
          </div>
          <div class="col-6">
           <% if book.title == info.title %>
            <span class="badge badge-warning"><%= "発売日:#{info.sales_date}" %></span>
            <span class="badge badge-success"><%= "著者: #{info.author}" %></span>
           <% end %> 
            <%= render partial: "books/tag", collection: book.tags, as: :tag %>
            <br>
            <div class="mt-2">
              <%= book.title %> 
            </div>
            <br>
            <div class = "theright">
             <small class="text-muted">
               <%= book.created_at.strftime('%Y/%m/%d') %>
             </small> 
            </div>          
          </div>
         </div>
       <div class="text-right position-absolute" style="top: 4px; right: 4px">
          <div class="btn-group">
            <button type="button" class="btn" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fas fa-ellipsis-v align-middle"></i>
            </button>
            <div class="dropdown-menu dropdown-menu-right text-middle">
              <%= link_to "タグ作成・削除", new_tag_path(book), class: "dropdown-item", remote: true %>
              <%= link_to "編集・タグ付け", edit_book_path(book), class: "dropdown-item", remote: true %>
              <%= link_to "削除", deletemodal_path(book), class: "dropdown-item text-danger", remote: true %>
            </div>
          </div>
       </div>
      </div>
    </div>    
  <% end %>
<% else %>
  <div class="card mb-3" data-model_name="<%= Book.model_name.singular %>"
  data-id="<%= book.id %>">
    <div class="card-body">
     <p class="card-text">
       <div class="cen">
        <div class="col-2">
         <p class="badge badge-danger">no-image</p>
        </div>
        <div class="col-6">
          <%= render partial: "books/tag", collection: book.tags, as: :tag %>
          <br>
          <div class="mt-2">
              <%= book.title %> 
          </div>
          <br>
          <div class = "theright">
             <small class="text-muted">
               <%= book.created_at.strftime('%Y/%m/%d') %>
             </small> 
          </div>          
        </div>
       </div>
     <div class="text-right position-absolute" style="top: 4px; right: 4px">
        <div class="btn-group">
          <button type="button" class="btn" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-ellipsis-v align-middle"></i>
          </button>
          <div class="dropdown-menu dropdown-menu-right text-middle">
            <%= link_to "タグ作成・削除", new_tag_path(book), class: "dropdown-item", remote: true %>
            <%= link_to "編集・タグ付け", edit_book_path(book), class: "dropdown-item", remote: true %>
            <%= link_to "削除", deletemodal_path(book), class: "dropdown-item text-danger", remote: true %>
          </div>
        </div>
     </div>
    </div>
  </div>
<% end %>

app/views/books/_destroy.html.erb
<div class="modal fade" id="bookModal" tabindex="-1" role="dialog" aria-labelledby="bookModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <%= form_with(model: book, method: :delete, remote: true) do |form| %>
        <div class="modal-header">
          <h5 class="modal-title" id="bookModal">本当に削除しますか？</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <% if book.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(book.errors.count, "件のエラー") %> があります。以下の理由で登録できません:</h2>
              <ul>
                <% book.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
        <div class="modal-footer actions">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
          <button type="submit" class="btn btn-outline-danger">削除</button>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/books/_edit_form.html.erb
<div class="modal fade" id="bookModal" tabindex="-1" role="dialog" aria-labelledby="bookModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <%= form_with(model: book, remote: true) do |form| %>
        <div class="modal-header">
          <h5 class="modal-title" id="bookModal"><%= "#{params[:action].camelize} #{book.model_name.human}title" %></h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <% if book.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(book.errors.count, "件のエラー") %> があります。以下の理由で登録できません:</h2>
              <ul>
                <% book.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <div class="field">
            <%= form.label :title %>
            <%= form.text_field :title %> 
          </div>
          <!--collection_check_boxes-->
          <div class="field">
            <%= form.collection_check_boxes :tag_ids, current_user.tags, :id, :name do |b| %>
              <%= b.label(class: "form-check") do %>
                <%= b.check_box(class: "form-check-input") %>
                <div class="btn btn-secondary" >
              <%= b.text %>
                </div>
              <% end %>
            <% end %>
          </div>
         </div>
        <div class="modal-footer actions">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
          <%= form.submit "タグ付け"%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/books/_form.html.erb
<div class="modal fade" id="bookModal" tabindex="-1" role="dialog" aria-labelledby="bookModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <%= form_with(model: book, remote: true) do |form| %>
        <div class="modal-header">
          <h5 class="modal-title" id="bookModal"><%= "#{params[:action].camelize} #{book.model_name.human}title" %></h5><h5 id="count" style="margin-left:auto"></h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <% if book.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(book.errors.count, "件のエラー") %> があります。以下の理由で登録できません:</h2>
              <ul>
                <% book.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
            <div class="modal-footer actions">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
          <% else %>
          <div class="field">
            <%= form.label :title %>
            <%= form.text_field :title, placeholder: "登録する本のタイトルを入力してください。"  %>
          </div>
           <!--collection_check_boxes-->
          <div class="field">
            <%= form.collection_check_boxes :tag_ids, current_user.tags, :id, :name do |b| %>
              <%= b.label(class: "form-check") do %>
                <%= b.check_box(class: "form-check-input") %>
                <div class="btn btn-secondary" >
              <%= b.text %>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
        <div class="modal-footer actions">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
          <%= form.submit "タイトルを登録"%>
        </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/books/_index_books.erb
<% if @books_info.present? %>
  <% @books_info.zip(@books) do |info, book| %>
    <div class="card mb-3 " data-model_name="<%= Book.model_name.singular %>"
    data-id="<%= book.id %>">
      <div class="card-body">
       <p class="card-text">
         <div class="cen">
          <div class="col-2">
           <% if book.title == info.title %>
            <%= link_to (image_tag(info.medium_image_url)), info.item_url %>
           <% else %>
           <p class="badge badge-danger">no-image</p>
           <% end %> 
          </div>
          <div class="col-6">
           <% if book.title == info.title %>
            <span class="badge badge-warning"><%= "発売日:#{info.sales_date}" %></span>
            <span class="badge badge-success"><%= "著者: #{info.author}" %></span>
           <% end %> 
            <%= render partial: "books/tag", collection: book.tags, as: :tag %>
            <br>
            <div class="mt-2">
              <%= book.title %> 
            </div>
            <br>
            <div class = "theright">
             <small class="text-muted">
               <%= book.created_at.strftime('%Y/%m/%d') %>
             </small> 
            </div>         
          </div>
         </div>
       <div class="text-right position-absolute" style="top: 4px; right: 4px">
          <div class="btn-group">
            <button type="button" class="btn" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fas fa-ellipsis-v align-middle"></i>
            </button>
            <div class="dropdown-menu dropdown-menu-right text-middle">
              <%= link_to "タグ作成・削除", new_tag_path(book), class: "dropdown-item", remote: true %>
              <%= link_to "編集・タグ付け", edit_book_path(book), class: "dropdown-item", remote: true %>
              <%= link_to "削除", deletemodal_path(book), class: "dropdown-item text-danger", remote: true %>
            </div>
          </div>
       </div>
      </div>
    </div>    
  <% end %>
<% else %>
 <% @books.each do |book| %>
  <div class="card mb-3" data-model_name="<%= Book.model_name.singular %>"
  data-id="<%= book.id %>">
    <div class="card-body">
     <p class="card-text">
       <div class="cen">
        <div class="col-2">
         <p class="badge badge-danger">no-image</p>
        </div>
        <div class="col-6">
          <%= render partial: "books/tag", collection: book.tags, as: :tag %>
          <br>
          <div class="mt-2">
              <%= book.title %> 
          </div>
          <br>
          <div class = "theright">
             <small class="text-muted">
               <%= book.created_at.strftime('%Y/%m/%d') %>
             </small> 
          </div>
        </div>
       </div>
     <div class="text-right position-absolute" style="top: 4px; right: 4px">
        <div class="btn-group">
          <button type="button" class="btn" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-ellipsis-v align-middle"></i>
          </button>
          <div class="dropdown-menu dropdown-menu-right text-middle">
            <%= link_to "タグ作成・削除", new_tag_path(book), class: "dropdown-item", remote: true %>
            <%= link_to "編集・タグ付け", edit_book_path(book), class: "dropdown-item", remote: true %>
            <%= link_to "削除", deletemodal_path(book), class: "dropdown-item text-danger", remote: true %>
          </div>
        </div>
     </div>
    </div>
  </div>
 <% end %>
<% end %>

app/views/books/_modalsearch_form.html.erb
<div class="modal fade" id="bookModal" tabindex="-1" role="dialog" aria-labelledby="bookModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <%= form_with(model: books, method: :get, url: search_path, remote: true) do |form| %>
        <div class="modal-header">
          <h5 class="modal-title" id="bookModal"><%= "検索結果" %></h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="book-list">
              <% books.each do |books| %>
              <p><%= "〇 #{books.title}" %></p>
              <% end %>
          </div> 
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/books/_notcase.js.erb
<div class="modal fade" id="bookModal" tabindex="-1" role="dialog" aria-labelledby="bookModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <%= form_with(url: search_path, remote: true) do |form| %>
        <div class="modal-header">
          <h5 class="modal-title" id="bookModal"><%= "検索結果" %></h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="book-list">
               <p>一致するものは、ありません。</p>
          </div> 
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/books/_tag.html.erb
<!--タグが一列に並ぶように-->
<div class="d-inline-block overflow-wrap">
  <span class="badge badge-primary"><%= tag.name %></span>
</div>

app/views/books/deletemodal.js.erb
<!--// modalを閉じる処理-->
$("#bookModal").modal("hide");
$("body").removeClass("modal-open");
$(".modal-backdrop").remove();

<!--// 削除確認モーダル画面-->
$("#modalArea").html(
  "<%= j(render 'destroy', book: @book) %>"
);

<!--// モーダル表示-->
$("#modalArea").find(".modal").modal("show");

app/views/books/destroy.js.erb
<!--// modalを閉じる処理-->
$("#bookModal").modal("hide");
$("body").removeClass("modal-open");
$(".modal-backdrop").remove();

<!--// モーダル表示-->
$("#modalArea").find(".modal").modal("show");

<!--// 画面の書き換え-->
$('[data-model_name="book"]').filter('[data-id="<%= @book.id %>"]').remove();

app/views/books/edit.js.erb
$("#bookModal").modal("hide");
$('body').removeClass('modal-open');
$('.modal-backdrop').remove();

<!--// モーダル追加-->
$("#modalArea").html(
  "<%= j(render 'edit_form', book: @book) %>"
);

<!--// フォームにフォーカス-->
<!--//modalAreaのなかから modalを探してきて、-->
$("#modalArea").find(".modal").on('shown.bs.modal', () => {
  $("#modalArea").find("form input[type=text]")[0].focus();
})

<!--// モーダル表示-->
$("#modalArea").find(".modal").modal("show");

app/views/books/index.html.erb
<div class="book-title-area px-3 py-2 text-center bg-white">
  <h1>Bookshelf</h1>
  <%= link_to new_book_path, title: "New", class: "btn p-0 text-dark", remote: true do %>
    <span class="align-middle btn btn-outline-success">本のタイトルを登録</span>
  <% end %>
  <%  if current_user.books.exists?  %>
      <% if user_signed_in? %>
        <span class="align-middle pr-1 btn btn-outline-danger">
          <div class="search_form">
             <%= form_with(model: @book, method: :get, url: search_path, remote: true) do |form| %>
                <%= form.text_field :keyword, placeholder: "本のタイトルを入力" %>
                <%= form.select :search, options_for_select([["完全一致","perfect_match"], ["部分一致","partial_match"]]) %>
                <%= form.submit "検索", class: "btn btn-primary" %>
              <% end %>
          </div>
        </span>
      <% end %>
  <% end %>
	<!--実際にbookが表示される部分-->
</div>
<div class="text-center py-3 books-index-area" id="booksIndex">
<% if @books.present? %>  
<%= render 'index_books' %>
<% end %>
</div>

<script>
$(function() {
    setTimeout("$('#alertfadeout').fadeOut('slow')", 500);
  });
</script>

app/views/books/search.js.erb
$("#bookModal").modal("hide");
$('body').removeClass('modal-open');
$('.modal-backdrop').remove();

<!--// モーダル追加-->
<% if @books.blank? or nil %>
$("#modalArea").html("<%= j(render 'notcase', books: @books) %>");
<% else %>
$("#modalArea").html("<%= j(render 'modalsearch_form', books: @books) %>");
<% end %>



<!--// モーダル表示-->
$("#modalArea").find(".modal").modal("show");


  
  

app/views/books/update.js.erb
<!--// モーダルを閉じる処理-->
$("#bookModal").modal("hide");
$('body').removeClass('modal-open');
$('.modal-backdrop').remove();

<!--// Rails @status => true 画面の書き換え : false モーダルを再度表示-->
<% if @status %>
$('[data-model_name="book"]').filter('[data-id="<%= @book.id %>"]').replaceWith("<%= j(render @book) %>")
<% else %>
$("#modalArea").html("<%= j(render 'form', book: @book) %>")
$("#modalArea").find(".modal").modal('show')
<% end %>