config/routes.rb
Rails.application.routes.draw do
  resources :tags
  resources :books
  resources :rakutenbooks, only: [:new, :index]
  
  
  get 'search' => 'books#search'
  get 'loading' => 'tags#loading'

  # modalで削除確認画面実装(book)
  get 'books/:id/deletemodal' => 'books#deletemodal', as: 'deletemodal'
  # modalで削除確認画面実装(tag)
  get 'tags/:id/deletemodal' => 'tags#tagdeletemodal', as: 'tagdeletemodal'

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'   
  } 

  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy" 
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root to: "home#index"
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :user
  has_many :book_tags, dependent: :destroy
  has_many :books, through: :book_tags

  validates :name, presence: true, uniqueness: { scope: :user }
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_tag, only: [:edit, :update, :tagdeletemodal, :destroy]
  before_action :api, only: [:update, :destroy]


  # GET /tags
  def index
    @tags = current_user.tags.all
  end

  # GET /tags/new
  def new
    @tag = current_user.tags.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  def create
    @tag = current_user.tags.new(tag_params)

    if @tag.save
       @status = true
    else
       @status = false
    end
  end

  # PATCH/PUT /tags/1
  def update
    if @tag.update(tag_params)
       @status = true
    else
       @status = false
    end
  end

  def tagdeletemodal
  end

  # DELETE /tags/1
  def destroy
    if @tag.destroy
      @status = true
      redirect_to books_path
    else
      @status = false
    end
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
     @tag = current_user.tags.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def tag_params
      params.require(:tag).permit(:name, :user_id)
    end

    def api
      #books
       sortbooks = Book.order(:created_at)
       @allbooks = current_user.books.all
       @total_count = current_user.books.count
       @rakuten_books_full = []
       @books_full = []
       if @total_count >= 1 
         @allbooks.each do |book|
           @books_full.push(book)
         end
         @books = @books_full
       else
         @books = @allbooks
       end
       #books_info
       if @total_count >= 1
        (@total_count).times do |i|
          @title = current_user.books.pluck(:title)[i]
            @rakuten_books = RakutenWebService::Books::Book.search(title: @title, sort: '-releaseDate', hits: 1)
              if @rakuten_books.response["hits"] == 0
                   @rakuten_books = RakutenWebService::Books::Book.search(title: "クジラの進化", sort: '-releaseDate', hits: 1)
                     @rakuten_books.each do |book|
                       @rakuten_books_full.push(book)
                     end
              else
                 @rakuten_books = RakutenWebService::Books::Book.search(title: @title, sort: '-releaseDate', hits: 1)
                   @rakuten_books_title = @rakuten_books.params[:title]
                     @rakuten_books.each do |book|
                       @rakuten_books_full.push(book)
                     end
              end
        end
        @books_info = @rakuten_books_full
      else
        @books_info = nil
      end
     end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_destroy.html.erb
<div class="modal fade" id="bookModal" tabindex="-1" role="dialog" aria-labelledby="bookModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <%= form_with(model: tag, method: :delete, remote: true) do |form| %>
        <div class="modal-header">
          <h5 class="modal-title" id="bookModal">本当に削除しますか？</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <% if tag.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(tag.errors.count, "件のエラー") %> があります。以下の理由で登録できません:</h2>
              <ul>
                <% tag.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
        <div class="modal-footer actions">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
          <button type="submit" class="btn btn-outline-danger btndel" id="">削除</button>
           <button id="hidden" class="btn btn-danger ary" type="button" disabled>
             <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
            Loading...
           </button>
        </div>
      <% end %>
    </div>
  </div>
</div>

<script>
  $('.btndel').on('click',function(){
    $('.btndel').attr('id', 'hidden');
    $('.ary').attr('id', 'append');
  })
</script>

app/views/tags/_edit_form.html.erb
<div class="modal fade" id="tagModal" tabindex="-1" role="dialog" aria-labelledby="tagModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <%= form_with(model: tag, remote: true) do |form| %>
        <div class="modal-header">
          <h5 class="modal-title" id="tagModal"><%= "#{params[:action].camelize} #{tag.model_name.human}" %></h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <% if tag.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(tag.errors.count, "件のエラー") %> があります。以下の理由で登録できません:</h2>
              <ul>
                <% tag.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <div class="field">
            <%= form.label :name %>
            <%= form.text_field :name %>
          </div>
        </div>
        <div class="modal-footer actions">
          <%= link_to new_tag_path, remote: true do %>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <% end %>
          <%= form.submit "タグの修正", class: "btndel", id: "" %>
           <button id="hidden" class="btn btn-danger ary" type="button" disabled>
            <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
            Loading...
           </button>
        </div>
      <% end %>
    </div>
  </div>
</div>

<script>
  $('.btndel').on('click',function(){
    $('.btndel').attr('id', 'hidden');
    $('.ary').attr('id', 'append');
  })
</script>

app/views/tags/_form.html.erb
<div class="modal fade" id="dal" tabindex="-1" role="dialog" aria-labelledby="tagModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <%= form_with(model: tag, remote: true) do |form| %>
        <div class="modal-header">
          <h5 class="modal-title" id="tagModal"><%= "#{params[:action].camelize} #{tag.model_name.human}" %></h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <% if tag.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(tag.errors.count, "件のエラー") %>があります。以下の理由で登録できません:</h2>
              <ul>
                <% tag.errors.full_messages.each do |message| %>
                <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <div class="field">
            <%= form.label :name %>
            <%= form.text_field :name, placeholder: "作成したいタグの名前を入力してください。" %>
          </div>
         <%= render 'index' %>
          <div class="modal-footer actions">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= form.submit "タグを作成"%>
       </div>
      <% end %>
    </div>
  </div>
</div>

app/views/tags/_index.html.erb
<div id="tagIndex">
  <%= render partial: "tags/tag", collection: current_user.tags.select(&:persisted?), as: :tag %>
</div>

app/views/tags/_loading.html.erb
<div id="loading">
  <div id="loading_box">
    <div class="loading-one animation_loading">
      <p class="loading-txt">Loading</p>
    </div>
  </div>
</div> 

<script>
$("#modalArea").html(
  "<%= j(render 'books/index_books', book: @books) %>"
);
</script>

app/views/tags/_tag.html.erb
<div id="dprow" data-model_name="<%= Tag.model_name.singular %>" data-id="<%= tag.id %>">
  <%= link_to edit_tag_path(tag), remote: true do %>
    <div class="btn btn-secondary mr-1 mb-2"><%= tag.name %></div>
  <% end %>
  <%= link_to tagdeletemodal_path(tag), class: "text-danger", remote: true, data: {"turbolinks" => false} do %>
    <i class="fas fa-times text-danger"></i>
  <% end %>
</div>

app/views/tags/create.js.erb
<!--// 値をクリアしてfocusする-->
$('.field input#tag_name').val("")
$('.field input#tag_name').focus();

<!--// Rails @status => true 画面の書き換え : false モーダルを再度表示-->
<% if @status %>
$("#modalArea")
  .find("#tagIndex")
  .html('<%= j(render partial: "tags/tag", collection: current_user.tags.select(&:persisted?), as: :tag) %>')
<% else %>
<!--modalを閉じる処理-->
$("#tagModal").modal("hide");
$('body').removeClass('modal-open');
$('.modal-backdrop').remove();

<!--// モーダルの書き換え-->
$("#modalArea").html("<%= j(render 'tags/form', tag: @tag) %>")

<!--// モーダルを表示する。-->
$("#modalArea").find(".modal").modal('show')
<% end %>

app/views/tags/destroy.js.erb
<!--// モーダルの書き換え-->
$('[data-model_name="tag"]').filter('[data-id="<%= @tag.id %>"]').remove();

<!--// すでに表示されているbooksを書き換え-->
$('#booksIndex').html('<%= j(render partial: "loading", book: @books) %>')

app/views/tags/edit.js.erb
<!--modalを閉じる処理-->
$("#tagModal").modal("hide");
$('body').removeClass('modal-open');
$('.modal-backdrop').remove();

<!--// モーダルの書き換え-->
$("#modalArea").html("<%= j(render 'edit_form', tag: @tag) %>")

<!--// フォームにフォーカス-->
$("#modalArea").find(".modal").on('shown.bs.modal', () => {
    $("#modalArea").find("form input[type=text]")[0].focus();
})
<!--モーダルを表示-->
$("#modalArea").find(".modal").modal('show')

app/views/tags/loading.js.erb
$("#modalArea").html(
  "<%= j(render 'books/index_books', book: @book) %>"
);

app/views/tags/new.js.erb
<!--modalを閉じる処理-->
$("#tagModal").modal("hide");
$('body').removeClass('modal-open');
$('.modal-backdrop').remove();

<!--// モーダルの書き換え-->
$("#modalArea").html("<%= j(render 'form', tag: @tag) %>")

<!--// フォームにフォーカス-->
$("#modalArea").find(".modal").on('shown.bs.modal', () => {
    $("#modalArea").find("form input[type=text]")[0].focus();
})
<!--モーダルを表示-->
$("#modalArea").find(".modal").modal('show')

app/views/tags/tagdeletemodal.js.erb
<!--// modalを閉じる処理-->
$("#tagModal").modal("hide");
$("body").removeClass("modal-open");
$(".modal-backdrop").remove();

<!--// 削除確認モーダル画面-->
$("#modalArea").html(
  "<%= j(render 'destroy', tag: @tag) %>"
);

<!--// モーダル表示-->
$("#modalArea").find(".modal").modal("show");

app/views/tags/update.js.erb
<!--modalを閉じる処理-->
$("#tagModal").modal("hide");
$('body').removeClass('modal-open');
$('.modal-backdrop').remove();

<% if @status %>
<!--// すでに表示されているbooksを書き換え-->
$('#booksIndex').html('<%= j(render partial: "books/index_books", book: @books) %>')

<!--// new tagモーダル画面に戻る（その際、作ったタグが表示されるようにtag:Tag.new）-->
$("#modalArea").html("<%= j(render 'form', tag: Tag.new) %>")

<!--// フォームにフォーカス-->
$("#modalArea").find(".modal").on('shown.bs.modal', () => {
    $("#modalArea").find("form input[type=text]")[0].focus();
})

<!--// モーダルを表示する。-->
$("#modalArea").find(".modal").modal('show')

<% end %>