config/routes.rb
Rails.application.routes.draw do
  resources :tags
  resources :books
  resources :rakutenbooks, only: [:new, :index]
  
  
  get 'search' => 'books#search'
  get 'loading' => 'tags#loading'

  # modalで削除確認画面実装(book)
  get 'books/:id/deletemodal' => 'books#deletemodal', as: 'deletemodal'
  # modalで削除確認画面実装(tag)
  get 'tags/:id/deletemodal' => 'tags#tagdeletemodal', as: 'tagdeletemodal'

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'   
  } 

  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy" 
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root to: "home#index"
end

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="fixed-top mt-5 container">
    <div id = "alertfadeout" class="alert <%= bs4_bgcolor_for(key) %> alert-dismissable fade show my-3">
      <%= value %>
      <button class="close" data-dismiss="alert">x</button>
    </div>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="bg-light d-flex flex-column justify-content-end align-items-end fixed-bottom">
 <%= link_to "#" do %>
    <%= image_tag "/assets/logo.png", size: "50x50", class: "img-logo" %>
 <% end %>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <%= link_to 'Bookshelf', root_path, class: "navbar-brand", data: {"turbolinks" => false} %>
  <button
    class="navbar-toggler"
    type="button"
    data-toggle="collapse"
    data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
<!--// もしユーザーがログインしているならば下記を表示-->
      <%  if user_signed_in?  %>
        <%  if current_page?(rakutenbooks_path) or current_page?(new_rakutenbook_path)  %>
          <li class="nav-item ml-auto">
            <%= link_to "Bookshelf", books_path, method: :get, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item ml-auto">
            <%= link_to "楽天books", new_rakutenbook_path, method: :get, class: "nav-link" %>
          </li>
        <% end %>  
          <li class="nav-item ml-auto">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
<!--//ログインしていないのなら下記を表示-->
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookshelf</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <%= render "layouts/header" %>
      <%= render "layouts/flash" %>
      <div id="modalArea"></div>
      <main>
        <div class="mflame">
          <%= yield %>
        </div>
      </main>
      <%= render "layouts/footer" %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bookshelf</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <%= render "layouts/flash" %>
    <main class="d-flex align-items-center w-100 h-100">
      <div class="container">
        <div class="cen">
          <div class="col-11 col-lg-5 jumbotron mx-auto mt-4" style="box-shadow: 0 0 5px 5px rgba(0, 0, 0, 0.2)">
            <%= yield %>
          </div>
        </div>
      </div>
    </main>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bookshelf</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div id="loading">
      <div id="loading_box">
        <div class="loading-one animation_loading ">
          <%= image_tag "/assets/logo.png", class: "loading_image" %>
        </div>
      </div>
    </div>
      <%= render "layouts/flash" %>
       <div id="wrapper">
        <%= yield %>
         <div class="mt-5">
          <ul class="pro_merit_ul ">
            <div class= "mb-3 col-sm-6 col-md-6 col-lg-6 col-xl-6">
              <li class="pro_merit_li">
              <%= image_tag "/assets/reg.png", class: "imgs" %> 
              </li>
            </div>
            <div class= "mb-3 col-sm-6 col-md-6 col-lg-6 col-xl-6">
              <li class="pro_merit_li">
              <%= image_tag "/assets/search.png", class: "imgs" %> 
              </li>
            </div>
          </ul>
         </div>
       </div>
  </body>
</html>